### ISSUE TITLE
 FloatProperty && IntProperty's border problem

### ISSUE THREAD

**Issue by scgm0** [Jummit/property-panel#2]
![image](https://github.com/Jummit/property-panel/assets/52148221/a8ec313e-053d-4c4b-a63d-02642222eb09)

**Comment by scgm0** [comment]
PropertyPanel/@ScrollContainer@106.clip_contents = false
![image](https://github.com/Jummit/property-panel/assets/52148221/19fa07a8-53bd-47ba-869e-53a8ec76ff7f)

应该修改此为默认值？

**Comment by Jummit** [comment]
Can you share a minimal reproduction example so I can take a look at what the problem is?

**Comment by scgm0** [comment]
> Can you share a minimal reproduction example so I can take a look at what the problem is?您能否分享一个最小的复制示例，以便我看看问题出在哪里？



> clip_contents

The problem is just that ScrollContainer's clip_contents defaults to true, so it doesn't draw beyond.

**Comment by scgm0** [comment]
> clip_contents = false

You're right, can't use clip_contents = false, maybe should set the margins

**Comment by scgm0** [comment]
> Can you share a minimal reproduction example so I can take a look at what the problem is?您能否分享一个最小的复制示例，以便我看看问题出在哪里？

You're right, can't use clip_contents = false, maybe should set the margins
